### ISSUE TITLE
It can only extract fixed frames from each video?

### ISSUE THREAD

**Issue by WillQuCD** [voletiv/lipreading-in-the-wild-experiments#4]
Thanks for your contribution!

I found it can only extract fixed frames from each video? right?
VIDEO_FRAMES_PER_WORD = 30
Does this mean I can only extract 30 frames from each video even though the durations of each video are different?
Thanks!

**Comment by voletiv** [comment]
No, it simply means every video has 30 frames in total.

I extract the duration of each word from its metadata separately. I then convert it into number of frames for uttering that word (by multiplying with the FPS of the video).

Because each word is centred in each video, I note the frame numbers (indexes) of the utterance of the word as "15 - (duration of word)*FPS" to "15 + (duration of word)*FPS". Instead of "15", I mark it as "VIDEO_FRAMES_PER_WORD/2". You can see it in the code:

```
wordFrameNumbers = range(math.floor(VIDEO_FRAMES_PER_WORD/2 - wordDuration*VIDEO_FPS/2),
        math.ceil(VIDEO_FRAMES_PER_WORD/2 + wordDuration*VIDEO_FPS/2) + 1)
```

(LRW dataset was designed such that each word is centred in the video. If a word lasts 2 seconds and it's a 4-second video, that means the word is uttered from 1sec to 3sec.)
